# Generated by Django 3.2.5 on 2021-07-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoundname',
            name='nome_completo',
            field=models.CharField(max_length=70),
        ),
    ]
