# Generated by Django 3.2.5 on 2021-07-06 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_nome_completo_compoundname_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compoundname',
            old_name='fullname',
            new_name='nome_completo',
        ),
    ]
