# Generated by Django 3.2.5 on 2021-07-06 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_fullname_compoundname_nome_completo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compoundname',
            old_name='nome_completo',
            new_name='nomeCompleto',
        ),
    ]
