# Generated by Django 3.2.5 on 2021-07-06 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_nome_completo_compoundname_nomecompleto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compoundname',
            old_name='nomeCompleto',
            new_name='nome_Completo',
        ),
    ]
